(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,lanes=[200,360,520];
const cfg=window.GHOST_CONFIG||{},db=(window.supabase&&cfg.supabaseUrl&&cfg.supabasePublishableKey)?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey):null;
const KEY='ghostRush-v4',local=JSON.parse(localStorage.getItem(KEY)||'{}');
local.coins??=420;local.displayName??=`Ghost${Math.floor(1000+Math.random()*8999)}`;local.bests??={};local.modePlays??={};local.selectedMode??='speed_grid';local.xp??=0;
let user=null,online=false,profile={display_name:local.displayName,coins:local.coins,rank_points:0,xp:local.xp},leaderboard=[],challenge=null,lastRunId=null,currentGhost={name:'Ghost',score:21.43,actions:[]},mode=local.selectedMode;
let playing=false,countdownRunning=false,start=0,last=0,elapsed=0,distance=0,lane=1,actions=[],objects=[],particles=[],ghostLane=1,ghostActionIndex=0,slowUntil=0,boostUntil=0,touchStartX=null,runShards=0,combo=1,maxCombo=1,shake=0;
let sliceRunning=false,sliceStart=0,slicePos=0,sliceTarget=50,sliceWidth=8,sliceRaf=0,audioCtx=null;
const RUN_DISTANCE=7600,BASE_SPEED=325;
function persist(){localStorage.setItem(KEY,JSON.stringify(local))} function daySeed(){const d=new Date();return Number(`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`)}
function rng(s){let t=s+0x6D2B79F5;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^t>>>15,1|t);r^=r+Math.imul(r^r>>>7,61|r);return((r^r>>>14)>>>0)/4294967296}}
function rankFor(rp){if(rp>=2500)return'Phantom';if(rp>=1200)return'Diamond';if(rp>=600)return'Platinum';if(rp>=250)return'Gold';if(rp>=80)return'Silver';return'Rookie'}
function levelFor(xp){return Math.floor((xp||0)/120)+1} function levelProgress(xp){return((xp||0)%120)/120*100}
function formatScore(v,m=mode){return m==='perfect_slice'?`${Number(v).toFixed(2)}%`:`${Number(v).toFixed(2)}s`} function scoreToDb(v){return Math.round(v*1000)} function scoreFromDb(ms){return ms/1000}
function escapeHtml(v){return String(v??'Ghost').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));$('#nav').style.display=['speedGame','sliceGame','result'].includes(id)?'none':'grid';scrollTo(0,0)}
function setOnline(v,label){online=v;$('#onlineDot').classList.toggle('live',v);$('#onlineLabel').textContent=label||(v?'online':'local')}
function initAudio(){if(audioCtx)return;try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch(_){}} function sfx(f=440,d=.06,type='sine',gain=.03){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.value=gain;o.connect(g);g.connect(audioCtx.destination);const n=audioCtx.currentTime;g.gain.setValueAtTime(gain,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.start(n);o.stop(n+d)} function haptic(p=18){try{navigator.vibrate?.(p)}catch(_){}}
function bestKey(m=mode){return`${daySeed()}:${m}`} function getBest(m=mode){return local.bests[bestKey(m)]?.score??null}
function markPlayed(m){const k=String(daySeed());local.modePlays[k]??={};local.modePlays[k][m]=true;persist()} function missionCount(){const p=local.modePlays[String(daySeed())]||{};return Number(!!p.speed_grid)+Number(!!p.perfect_slice)}
function selectMode(m,fromChallenge=false){mode=m;local.selectedMode=m;persist();$$('.gameCard').forEach(c=>c.classList.toggle('selected',c.dataset.mode===m));$('#playBtn').textContent=m==='speed_grid'?'▶ PLAY SPEED GRID':'✂️ PLAY PERFECT SLICE';$('#leaderboardTitle').textContent=m==='speed_grid'?'👑 Speed Grid leaderboard':'👑 Perfect Slice leaderboard';$('#fullBoardTitle').textContent=m==='speed_grid'?'Speed Grid — Daily':'Perfect Slice — Daily';renderLocal();if(online&&!fromChallenge)loadLeaderboard().then(renderBoards)}
async function boot(){selectMode(mode);$('#dailySeedLabel').textContent=`#${daySeed()}`;$('#displayName').value=local.displayName;renderLocal();if(!db){setOnline(false,'local');return}try{let{data:s}=await db.auth.getSession();if(!s.session){const{data,error}=await db.auth.signInAnonymously({options:{data:{display_name:local.displayName}}});if(error)throw error;s={session:data.session}}user=s.session.user;setOnline(true,'online');await ensureProfile();await loadChallenge();await loadLeaderboard();renderAll()}catch(e){console.warn(e);setOnline(false,'local');toast('Online mode unavailable — local play still works')}}
async function ensureProfile(){const{data,error}=await db.from('ghost_profiles').select('id,display_name,rank_points,coins,xp').eq('id',user.id).maybeSingle();if(error)throw error;if(!data){const ins=await db.from('ghost_profiles').insert({id:user.id,display_name:local.displayName,rank_points:0,coins:local.coins,xp:local.xp}).select().single();if(ins.error)throw ins.error;profile=ins.data}else profile=data;local.displayName=profile.display_name;local.coins=profile.coins;local.xp=profile.xp||0;persist()}
async function loadChallenge(){const code=new URLSearchParams(location.search).get('c');if(!code||!online)return;const c=await db.from('ghost_challenges').select('code,run_id').eq('code',code).maybeSingle();if(c.error||!c.data)return;const r=await db.from('ghost_runs').select('id,user_id,player_name,elapsed_ms,actions,daily_seed,game_mode').eq('id',c.data.run_id).single();if(r.error||!r.data)return;challenge={code,...r.data};selectMode(r.data.game_mode||'speed_grid',true);currentGhost={name:r.data.player_name,score:scoreFromDb(r.data.elapsed_ms),actions:Array.isArray(r.data.actions)?r.data.actions:[]};$('#challengeBanner').classList.add('show');$('#challengeTitle').textContent=`${r.data.player_name} challenged you 👻`;$('#challengeText').textContent=`Beat ${formatScore(currentGhost.score,mode)} in ${mode==='speed_grid'?'Speed Grid':'Perfect Slice'}.`;$('#playBtn').textContent=`⚡ BEAT ${r.data.player_name.toUpperCase()}`}
async function loadLeaderboard(){if(!online)return;const{data,error}=await db.from('ghost_runs').select('id,user_id,player_name,elapsed_ms,actions,game_mode').eq('daily_seed',daySeed()).eq('game_mode',mode).order('elapsed_ms',{ascending:true}).limit(30);if(error){console.warn(error);return}const seen=new Set();leaderboard=[];for(const r of data||[])if(!seen.has(r.user_id)){seen.add(r.user_id);leaderboard.push(r)};if(!challenge&&leaderboard.length){const g=leaderboard.find(r=>r.user_id!==user?.id)||leaderboard[0];currentGhost={name:g.player_name,score:scoreFromDb(g.elapsed_ms),actions:Array.isArray(g.actions)?g.actions:[]}}}
function renderLocal(){const best=getBest();$('#coins').textContent=online?(profile.coins??local.coins):local.coins;$('#bestLabel').textContent=best==null?'--':formatScore(best);$('#levelLabel').textContent=levelFor(online?(profile.xp||0):local.xp);$('#xpLabel').textContent=`${online?(profile.xp||0):local.xp} XP`;const rp=profile.rank_points||0;$('#rankLabel').textContent=rankFor(rp);$('#rankPoints').textContent=`${rp} RP`;const mc=missionCount();$('#missionText').textContent=`${mc}/2`;$('#missionProgress').style.width=`${mc/2*100}%`;$('#profileGridBest').textContent=getBest('speed_grid')==null?'--':formatScore(getBest('speed_grid'),'speed_grid');$('#profileSliceBest').textContent=getBest('perfect_slice')==null?'--':formatScore(getBest('perfect_slice'),'perfect_slice')}
function renderAll(){renderLocal();const xp=profile.xp||0,rp=profile.rank_points||0;$('#profileLevel').textContent=`Level ${levelFor(xp)}`;$('#profileXp').textContent=`${xp} XP`;$('#profileRank').textContent=rankFor(rp);$('#profileRp').textContent=`${rp} RP`;$('#levelProgress').style.width=`${levelProgress(xp)}%`;$('#profileCoins').textContent=profile.coins??local.coins;$('#displayName').value=profile.display_name||local.displayName;$('#profileId').textContent=online?`online • ${String(user.id).slice(0,8)}`:'local player';renderBoards()}
function renderBoards(){const rows=leaderboard.length?leaderboard.slice(0,10):[{player_name:'Nova',elapsed_ms:mode==='speed_grid'?21430:420,user_id:'a'},{player_name:'Vex',elapsed_ms:mode==='speed_grid'?22010:680,user_id:'b'},{player_name:local.displayName,elapsed_ms:scoreToDb(getBest()??(mode==='speed_grid'?23.17:1.1)),user_id:user?.id||'me'}];const html=rows.map((r,i)=>`<div class="boardRow ${r.user_id===user?.id?'you':''}"><span class="rankNo">${i+1}</span><span>${escapeHtml(r.player_name)}</span><span class="time">${formatScore(scoreFromDb(r.elapsed_ms),mode)}</span></div>`);$('#homeBoard').innerHTML=html.slice(0,5).join('');$('#fullBoard').innerHTML=html.join('')}
function pickGhost(){if(challenge)return currentGhost;if(online&&leaderboard.length){const g=leaderboard.find(x=>x.user_id!==user?.id)||leaderboard[0];return{name:g.player_name,score:scoreFromDb(g.elapsed_ms),actions:Array.isArray(g.actions)?g.actions:[]}}const b=getBest();if(b!=null)return{name:'YOUR BEST',score:b,actions:local.bests[bestKey()]?.actions||[]};return mode==='speed_grid'?{name:'GHOST',score:21.43,actions:[]}:{name:'GHOST',score:.80,actions:[]}}
async function playSelected(){initAudio();if(mode==='speed_grid')await startSpeed();else startSlice()}
function buildTrack(){const r=rng(challenge?.daily_seed||daySeed());objects=[];let d=620;while(d<RUN_DISTANCE-260){d+=210+r()*175;const roll=r();if(roll<.17)objects.push({lane:Math.floor(r()*3),dist:d,type:'boost',hit:false});else if(roll<.4)objects.push({lane:Math.floor(r()*3),dist:d,type:'shard',hit:false});else{const l=Math.floor(r()*3);objects.push({lane:l,dist:d,type:'block',hit:false});if(r()<.4)objects.push({lane:(l+1+Math.floor(r()*2))%3,dist:d+50,type:'shard',hit:false})}}}
async function startSpeed(){if(countdownRunning||playing)return;mode='speed_grid';currentGhost=pickGhost();buildTrack();elapsed=0;distance=0;lane=1;actions=[];particles=[];ghostLane=1;ghostActionIndex=0;slowUntil=0;boostUntil=0;runShards=0;combo=1;maxCombo=1;shake=0;$('#ghostName').textContent=currentGhost.name;$('#ghostTime').textContent=formatScore(currentGhost.score,'speed_grid').replace('s','');$('#youTime').textContent='0.00';$('#runShards').textContent='0';$('#comboLabel').textContent='COMBO x1';show('speedGame');countdownRunning=true;const c=$('#countdown');for(const t of['3','2','1','GO!']){c.textContent=t;c.classList.add('show');sfx(t==='GO!'?740:420,.08,'square',.025);await new Promise(r=>setTimeout(r,t==='GO!'?320:470));c.classList.remove('show');await new Promise(r=>setTimeout(r,70))}countdownRunning=false;playing=true;start=performance.now();last=start;requestAnimationFrame(speedLoop)}
function setLane(n){if(!playing)return;n=Math.max(0,Math.min(2,n));if(n!==lane){lane=n;actions.push({t:Number(elapsed.toFixed(3)),next:n});burst(lanes[n],H*.78,'#55eaff',10);sfx(280+lane*60,.04,'triangle',.02)}}
function burst(x,y,c,n=8){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*190,vy:(Math.random()-.5)*180,life:.55,c,size:3+Math.random()*5})}
function collide(){for(const o of objects){if(o.hit||Math.abs(o.dist-distance)>72||o.lane!==lane)continue;o.hit=true;if(o.type==='block'){slowUntil=elapsed+.7;distance=Math.max(0,distance-95);combo=1;shake=12;sfx(110,.12,'sawtooth',.05);haptic([25,20,25]);burst(lanes[lane],H*.78,'#ff5b7c',18)}else if(o.type==='boost'){boostUntil=elapsed+1.15;distance+=150;combo++;maxCombo=Math.max(maxCombo,combo);sfx(680,.08,'square',.03);haptic(20);burst(lanes[lane],H*.78,'#4ff0a0',16)}else{runShards++;combo++;maxCombo=Math.max(maxCombo,combo);$('#runShards').textContent=runShards;$('#comboLabel').textContent=`COMBO x${combo}`;sfx(540+combo*18,.05,'sine',.03);haptic(10);burst(lanes[lane],H*.75,'#ffd166',12)}}}
function speedLoop(now){if(!playing)return;const dt=Math.min(.034,(now-last)/1000);last=now;elapsed=(now-start)/1000;let sp=BASE_SPEED+Math.min(65,elapsed*2.7);if(elapsed<slowUntil)sp*=.6;if(elapsed<boostUntil)sp*=1.43;distance+=sp*dt;shake*=.88;while(ghostActionIndex<(currentGhost.actions||[]).length&&(currentGhost.actions[ghostActionIndex].t||0)<=elapsed){ghostLane=currentGhost.actions[ghostActionIndex].next;ghostActionIndex++}collide();updateParticles(dt);drawSpeed();$('#youTime').textContent=elapsed.toFixed(2);if(distance>=RUN_DISTANCE)return finishRun(elapsed,false,{shards:runShards,combo:maxCombo});if(elapsed>45)return finishRun(elapsed+1.2,true,{shards:runShards,combo:maxCombo});requestAnimationFrame(speedLoop)}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=100*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function drawSpeed(){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.clearRect(-20,-20,W+40,H+40);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0b1640');g.addColorStop(1,'#03050d');ctx.fillStyle=g;ctx.fillRect(-20,-20,W+40,H+40);const horizon=220;ctx.fillStyle='#081126';ctx.beginPath();ctx.moveTo(300,horizon);ctx.lineTo(420,horizon);ctx.lineTo(650,H);ctx.lineTo(70,H);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(90,130,230,.38)';ctx.lineWidth=3;for(const x of[280,440]){ctx.beginPath();ctx.moveTo(W/2+(x-W/2)*.16,horizon);ctx.lineTo(x,H);ctx.stroke()}for(let i=0;i<18;i++){const ph=((distance*.3+i*100)%1350)/1350,y=horizon+(H-horizon)*ph*ph,half=55+ph*260;ctx.strokeStyle=`rgba(72,118,222,${.05+.15*ph})`;ctx.beginPath();ctx.moveTo(W/2-half,y);ctx.lineTo(W/2+half,y);ctx.stroke()}for(const o of objects){const diff=o.dist-distance;if(diff<-200||diff>3000)continue;const y=H*.77-diff*.23,sc=Math.max(.22,1-diff/4100),x=lanes[o.lane];ctx.save();ctx.translate(x,y);ctx.scale(sc,sc);if(o.type==='block'){ctx.fillStyle=o.hit?'#68283b':'#ff466d';ctx.shadowBlur=25;ctx.shadowColor='#ff466d';ctx.beginPath();ctx.roundRect(-54,-28,108,56,12);ctx.fill()}else if(o.type==='boost'){ctx.strokeStyle='#4ff0a0';ctx.lineWidth=10;ctx.shadowBlur=28;ctx.shadowColor='#4ff0a0';ctx.beginPath();ctx.moveTo(-42,17);ctx.lineTo(0,-25);ctx.lineTo(42,17);ctx.stroke()}else{ctx.strokeStyle=o.hit?'#6d5f34':'#ffd166';ctx.lineWidth=9;ctx.shadowBlur=26;ctx.shadowColor='#ffd166';ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.stroke()}ctx.restore()}const gd=RUN_DISTANCE*Math.min(1,elapsed/Math.max(.01,currentGhost.score));let gy=H*.78-(gd-distance)*.065;gy=Math.max(150,Math.min(H*.78-75,gy));drawRunner(lanes[ghostLane],gy,true);drawRunner(lanes[lane],H*.78,false);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/.55);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;const prog=Math.min(1,distance/RUN_DISTANCE);ctx.fillStyle='#111a36';ctx.fillRect(78,H-34,564,10);const pg=ctx.createLinearGradient(78,0,642,0);pg.addColorStop(0,'#55eaff');pg.addColorStop(.6,'#8157ff');pg.addColorStop(1,'#ff4fd8');ctx.fillStyle=pg;ctx.fillRect(78,H-34,564*prog,10);ctx.restore()}
function drawRunner(x,y,ghost){ctx.save();ctx.translate(x,y);ctx.globalAlpha=ghost?.5:1;ctx.shadowBlur=ghost?32:24;ctx.shadowColor=ghost?'#8a6cff':'#55eaff';ctx.fillStyle=ghost?'rgba(129,87,255,.22)':'#101831';ctx.strokeStyle=ghost?'#a997ff':'#55eaff';ctx.lineWidth=6;ctx.beginPath();ctx.roundRect(-34,-38,68,78,24);ctx.fill();ctx.stroke();ctx.fillStyle=ghost?'#c9c1ff':'#ffd166';ctx.beginPath();ctx.roundRect(-23,-48,46,24,10);ctx.fill();ctx.restore()}
function startSlice(){mode='perfect_slice';if(sliceRunning)return;currentGhost=pickGhost();show('sliceGame');const r=rng((challenge?.daily_seed||daySeed())+991);sliceTarget=42+r()*16;sliceWidth=7+r()*4;$('#targetZone').style.left=`${sliceTarget-sliceWidth/2}%`;$('#targetZone').style.width=`${sliceWidth}%`;$('#sliceGhostName').textContent=currentGhost.name;$('#sliceGhostScore').textContent=formatScore(currentGhost.score,'perfect_slice');$('#sliceGhostLine').textContent=formatScore(currentGhost.score,'perfect_slice');$('#sliceYou').textContent='--';$('#sliceLive').textContent='READY';$('#sliceSub').textContent='Watch the marker, then tap SLICE';slicePos=0;sliceRunning=true;sliceStart=performance.now();cancelAnimationFrame(sliceRaf);sliceRaf=requestAnimationFrame(sliceLoop)}
function sliceLoop(now){if(!sliceRunning)return;const t=(now-sliceStart)/1000,raw=(t*48)%200;slicePos=raw<=100?raw:200-raw;$('#sliceMarker').style.left=`${slicePos}%`;$('#sliceLive').textContent=`${slicePos.toFixed(1)}%`;sliceRaf=requestAnimationFrame(sliceLoop)}
function doSlice(){if(!sliceRunning)return;initAudio();sliceRunning=false;cancelAnimationFrame(sliceRaf);const error=Math.abs(slicePos-sliceTarget);actions=[{tap:Number(slicePos.toFixed(3)),target:Number(sliceTarget.toFixed(3))}];$('#sliceYou').textContent=formatScore(error,'perfect_slice');$('#sliceLive').textContent=error<.6?'PERFECT!':error<1.5?'CLEAN!':error<3?'CLOSE!':'MISSED';$('#sliceSub').textContent=`Target ${sliceTarget.toFixed(1)}% • stopped at ${slicePos.toFixed(1)}%`;sfx(error<1?820:error<3?560:160,.14,error<3?'sine':'sawtooth',.05);haptic(error<1?[15,20,15]:35);setTimeout(()=>finishRun(error,false,{slicePos,target:sliceTarget}),420)}
async function finishRun(score,failed,meta={}){playing=false;sliceRunning=false;markPlayed(mode);const old=getBest(),isPB=!failed&&(old==null||score<old);if(isPB)local.bests[bestKey()]={score,actions};const won=!failed&&score<currentGhost.score,xpGain=failed?5:20+(won?15:0)+(isPB?10:0),rpGain=failed?0:(won?20:6),reward=failed?0:5+(won?10:0)+(isPB?15:0)+(mode==='speed_grid'?(meta.shards||0):0);local.xp+=xpGain;local.coins+=reward;persist();$('#resultHeadline').textContent=won?'YOU WIN!':'SO CLOSE!';$('#resultHeadline').className=`headline ${won?'win':'lose'}`;$('#resultTime').textContent=formatScore(score);$('#resultYou').textContent=formatScore(score);$('#resultGhost').textContent=formatScore(currentGhost.score);$('#resultGhostName').textContent=currentGhost.name;$('#pbText').textContent=isPB?'NEW PERSONAL BEST ⚡':won?'Ghost beaten. Send it back.':'Rematch and take it back.';$('#resultXp').textContent=`+${xpGain}`;$('#resultRp').textContent=`+${rpGain}`;$('#resultReward').textContent=`+${reward}`;show('result');renderLocal();if(online&&!failed){try{const ins=await db.from('ghost_runs').insert({user_id:user.id,player_name:profile.display_name||local.displayName,daily_seed:challenge?.daily_seed||daySeed(),elapsed_ms:scoreToDb(score),actions,game_mode:mode}).select('id').single();if(ins.error)throw ins.error;lastRunId=ins.data.id;profile.coins=(profile.coins||0)+reward;profile.rank_points=(profile.rank_points||0)+rpGain;profile.xp=(profile.xp||0)+xpGain;const up=await db.from('ghost_profiles').update({coins:profile.coins,rank_points:profile.rank_points,xp:profile.xp,updated_at:new Date().toISOString()}).eq('id',user.id);if(up.error)throw up.error;local.coins=profile.coins;local.xp=profile.xp;persist();await loadLeaderboard();renderAll()}catch(e){console.warn(e);toast('Saved locally; online save failed')}}else renderAll()}
async function shareChallenge(){if(!online||!lastRunId){toast('Finish an online run first');return}try{const c=await db.from('ghost_challenges').insert({run_id:lastRunId,created_by:user.id}).select('code').single();if(c.error)throw c.error;const u=new URL(location.href);u.search='';u.searchParams.set('c',c.data.code);const text=`${profile.display_name||local.displayName} challenged you in ${mode==='speed_grid'?'Speed Grid':'Perfect Slice'}. Beat ${$('#resultTime').textContent}.`;if(navigator.share)await navigator.share({title:'Ghost Rush Challenge',text,url:u.toString()});else{await navigator.clipboard.writeText(u.toString());toast('Challenge link copied')}}catch(e){console.warn(e);toast('Could not create challenge')}}
async function saveProfile(){const name=$('#displayName').value.trim().slice(0,20)||'Ghost';local.displayName=name;persist();if(online){const q=await db.from('ghost_profiles').update({display_name:name,updated_at:new Date().toISOString()}).eq('id',user.id).select().single();if(q.error){toast('Profile save failed');return}profile=q.data}toast('Profile saved');renderAll()}
$$('.gameCard').forEach(c=>c.onclick=()=>selectMode(c.dataset.mode));$('#playBtn').onclick=playSelected;$('#rematchBtn').onclick=playSelected;$('#shareBtn').onclick=shareChallenge;$('#homeBtn').onclick=()=>show('home');$('#leftBtn').onclick=()=>setLane(lane-1);$('#rightBtn').onclick=()=>setLane(lane+1);$('#sliceBtn').onclick=doSlice;$('#saveProfileBtn').onclick=saveProfile;$('#refreshBoardBtn').onclick=async()=>{if(online){await loadLeaderboard();renderBoards();toast('Leaderboard refreshed')}};canvas.addEventListener('pointerdown',e=>{initAudio();touchStartX=e.clientX});canvas.addEventListener('pointerup',e=>{if(touchStartX==null)return;const dx=e.clientX-touchStartX;if(Math.abs(dx)>24)setLane(lane+(dx>0?1:-1));else setLane(lane+(e.clientX<innerWidth/2?-1:1));touchStartX=null});addEventListener('keydown',e=>{initAudio();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')setLane(lane-1);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')setLane(lane+1);if(e.key===' '&&mode==='perfect_slice')doSlice()});$$('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.screen));boot();
})();